site_name: Language Design and Implementation
site_author: Eduardo Furlan
site_url: https://efurlanm.github.io/ldi/
copyright: CC BY 4.0 License
repo_name: LDI
repo_url: http://github.com/efurlanm/ldi/
docs_dir: docs-src
site_dir: docs
theme:
    name: material
    # squidfunk.github.io/mkdocs-material/setup/changing-the-colors/
    palette:
        primary: orange
        accent: orange
    font: false
    features:
        - header.autohide
plugins:
    - search
    - blog:
        post_readtime: false
extra_css:
    - css/extra.css
exclude_docs: |
    .*
    .git
